2000
1
1

;XXXX - SPI clock prescaler: 1000 = 0.625 MHz, 2000 = 1.25 MHz, 4000 = 2.5 MHz, 6000 = 3.75 MHz, 8000 = 5 MHz, ..., 16000 = 10 MHz
;X    - Console screen Debug print level: 0 = no screen Log, 1 = min screen Log, 2 = APDU and response shown on screen, 3 = all debug messages shown on screen
;X    - Log file Debug print level
